[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
minter = "8ubPzisSkpZ7NMcgK72MZUYfx4XcTL9wh9QaBtanGpLP"

[programs.devnet]
minter = "8ubPzisSkpZ7NMcgK72MZUYfx4XcTL9wh9QaBtanGpLP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/fudo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"